workflows:
  android-workflow:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      java: 11
      ndk: r21e
      vars:
        JAVA_HOME: "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli
      - name: Prebuild
        script: |
          cd NH-S19-App
          npx expo prebuild -p android --clean --non-interactive
      - name: Build APK
        script: |
          cd NH-S19-App/android
          ./gradlew assembleDebug
    artifacts:
      - NH-S19-App/android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - workdocing3@gmail.com
        notify:
          success: true
          failure: true